apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-app
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: prod-container
        image: nginx:latest
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: password
        - name: DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: endpoint
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: rds-credentials
              key: database